version: '3.9'

services:

  database:
    container_name: postgres_smb
    image: 'bitnami/postgresql:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app
    volumes:
      - $PWD/data/pg:/bitnami/postgresql    

  cash-book:    
    build: ./cash-book
    container_name: cash-book
    ports:
      - 3333:3333
    volumes:
      - ./cash-book:/usr/app
    depends_on:
      - database

  sm-business:
    build: ./sm-business
    container_name: sm-business
    ports:
      - 3000:3000
    volumes:
      - ./sm-business:/usr/app
    depends_on:
      - cash-book