version: '3.9'

services:

  database:
    container_name: postgres_smb
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=app

  cash-book:    
    build: .
    container_name: cash-book
    ports:
      - 3333:3333
    volumes:
      - ./cash-book:/usr/app
    depends_on:
      - database